// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIadMOfXAh1qn8ncCJq3k7Ad1THd1g-1I',
    appId: '1:76096569400:web:41c73ed57b940a970c66cd',
    messagingSenderId: '76096569400',
    projectId: 'flutterapplication1-817e4',
    authDomain: 'flutterapplication1-817e4.firebaseapp.com',
    storageBucket: 'flutterapplication1-817e4.appspot.com',
    measurementId: 'G-MR9QRFPS1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-vlewsjz0bofU3wAmKDBWkbX0Kjp2YE',
    appId: '1:76096569400:android:073744c0a6b054a80c66cd',
    messagingSenderId: '76096569400',
    projectId: 'flutterapplication1-817e4',
    storageBucket: 'flutterapplication1-817e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rp1zYAf6NvQOQhMfOeSDs8TzNUazaDU',
    appId: '1:76096569400:ios:b3d3d11b7ef31e6d0c66cd',
    messagingSenderId: '76096569400',
    projectId: 'flutterapplication1-817e4',
    storageBucket: 'flutterapplication1-817e4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0rp1zYAf6NvQOQhMfOeSDs8TzNUazaDU',
    appId: '1:76096569400:ios:a25de97cecaad26a0c66cd',
    messagingSenderId: '76096569400',
    projectId: 'flutterapplication1-817e4',
    storageBucket: 'flutterapplication1-817e4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
